KUY=int(input())
KUY1=int(input())
KUY2=int(input())
KUY3=int(input())
KUY4=int(input())

print("THAI = ",KUY)
print("MATH = ",KUY1)
print("ENGLISH = ",KUY2)
print("SCIENCE = ",KUY3)
print("SPORT = ",KUY4)
print("---")
print("GPA = ",(KUY+KUY1+KUY2+KUY3+KUY4)/10)